// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klbachhdrsnmdyjftgae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsYmFjaGhkcnNubWR5amZ0Z2FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjgzODIsImV4cCI6MjA2MTAwNDM4Mn0.qMnZ6zwu8E0vo_WQOltRZBZSMt5VSXSDoyxGNXKA3aQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);